name: test
on:
 push:
  branches:
   - main
env:
  bucket: codepipeline-us-east-1-535271855363 
  
jobs:
  s3packageupload:
   runs-on: ubuntu-latest
   steps:
    - name: git clone the repository
      uses: actions/checkout@v3
    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ secrets.aws_region }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
   
    - name: Make artifacts directory
      run: mkdir -p ./artifacts
      
    - name: Copy build to s3
      run: |
        zip -r ./artifacts/project.zip . -x node_modules/**\* .git/**\* dist/**\* dist/**\*     
        aws s3 sync ${GITHUB_WORKSPACE}/artifacts s3://${{ env.bucket }}/${GITHUB_REF#refs/heads/}/latest
    
